/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_demondk_mk_jni_JniUtil */

#ifndef _Included_com_test_demondk_mk_jni_JniUtil
#define _Included_com_test_demondk_mk_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_demondk_mk_jni_JniUtil
 * Method:    getIntFromJni
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_test_demondk_1mk_jni_JniUtil_getIntFromJni
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
