package com.cakes.demogpuimage;

import java.util.ArrayList;
import java.util.List;

public class FilterList {

    public static List<String> getList() {
        List<String> filterList = new ArrayList<>();
        filterList.add("Saturation-饱和度");
        filterList.add("Contrast");
        filterList.add("Brightness");
        filterList.add("Levels");
        filterList.add("Exposure");
        filterList.add("RGB");
        filterList.add("RGB Diation");
        filterList.add("Hue");
        filterList.add("White Balance");
        filterList.add("Monochrome");
        filterList.add("False Color");
        filterList.add("Sharpen");
        filterList.add("Transform Operation");
        filterList.add("Gamma");
        filterList.add("Highlights and Shadows");
        filterList.add("Haze");
        filterList.add("Sepia Tone");
        filterList.add("Color Inversion");
        filterList.add("Solarize");
        filterList.add("Vibrance");
        filterList.add("Luminance");
        filterList.add("Luminance Threshold");
        filterList.add("Pixellate");
        filterList.add("Halftone");
        filterList.add("Crosshatch");
        filterList.add("Sobel Edge Detection");
        filterList.add("Threshold Sobel EdgeDetection");
        filterList.add("Sketch Filter");
        filterList.add("Toon Filter");
        filterList.add("SmoothToon Filter");
        filterList.add("CGA Colorspace Filter");
        filterList.add("Posterize");
        filterList.add("Convolution 3x3");
        filterList.add("Emboss Filter");
        filterList.add("Laplacian");
        filterList.add("Chroma Keying");
        filterList.add("Kuwahara Filter");
        filterList.add("Vignette");
        filterList.add("Gaussian Blur");
        filterList.add("Box Blur");
        filterList.add("Bilateral Blur");
        filterList.add("Zoom Blur");
        filterList.add("Swirl Distortion");
        filterList.add("Bulge Distortion");
        filterList.add("Sphere Refraction");
        filterList.add("Glass Sphere Refraction");
        filterList.add("Dilation");
        filterList.add("Dissolve Blend");
        filterList.add("Chroma Key Blend");
        filterList.add("Add Blend");
        filterList.add("Divide Blend");
        filterList.add("Multiply Blend");
        filterList.add("Overlay Blend");
        filterList.add("Lighten Blend");
        filterList.add("Darken Blend");
        filterList.add("Color Burn Blend");
        filterList.add("Color Dodge Blend");
        filterList.add("Linear Burn Blend");
        filterList.add("Screen Blend");
        filterList.add("Difference Blend");
        filterList.add("Subtract Blend");
        filterList.add("Exclusion Blend");
        filterList.add("HardLight Blend");
        filterList.add("SoftLight Blend");
        filterList.add("Color Blend");
        filterList.add("Hue Blend");
        filterList.add("Saturation Blend");
        filterList.add("Luminosity Blend");
        filterList.add("Normal Blend");
        filterList.add("Source Over Blend");
        filterList.add("Alpha Blend");
        filterList.add("Non Maximum Suppression");
        filterList.add("Opacity");
        filterList.add("Weak Pixel Inclusion Filter");
        filterList.add("Color Matrix");
        filterList.add("Directional Sobel Edge Detection");
        filterList.add("Lookup");
        filterList.add("Tone Curve (*.acv files)");

        return filterList;
    }
}
